---

- name: networkd | Deploy .link configs
  template:
    src: networkd.j2
    dest: "/etc/systemd/network/{{ item.priority }}-{{ item.name }}.link"
    mode: 644
    owner: root
    group: root
  with_items: "{{ networkd.link | default([]) }}"
  register: networkd_deployed_link
  notify: networkd | Do {{ networkd_apply_action }}

- name: networkd | Deploy .netdev configs
  template:
    src: networkd.j2
    dest: "/etc/systemd/network/{{ item.priority }}-{{ item.name }}.netdev"
    mode: 644
    owner: root
    group: root
  with_items: "{{ networkd.netdev | default([]) }}"
  register: networkd_deployed_netdev
  notify: networkd | Do {{ networkd_apply_action }}

- name: networkd | Deploy .network configs
  template:
    src: networkd.j2
    dest: "/etc/systemd/network/{{ item.priority }}-{{ item.name }}.network"
    mode: 644
    owner: root
    group: root
  with_items: "{{ networkd.network | default([]) }}"
  register: networkd_deployed_network
  notify: networkd | Do {{ networkd_apply_action }}
